# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synch_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SynchWindow(object):
    def setupUi(self, SynchWindow):
        SynchWindow.setObjectName("SynchWindow")
        SynchWindow.resize(1126, 882)
        self.centralwidget = QtWidgets.QWidget(SynchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sliderAudio1 = QtWidgets.QSlider(self.centralwidget)
        self.sliderAudio1.setGeometry(QtCore.QRect(50, 170, 1031, 22))
        self.sliderAudio1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAudio1.setObjectName("sliderAudio1")
        self.labelAudio1Value = QtWidgets.QLabel(self.centralwidget)
        self.labelAudio1Value.setGeometry(QtCore.QRect(20, 170, 21, 16))
        self.labelAudio1Value.setObjectName("labelAudio1Value")
        self.imageAudio1 = QtWidgets.QLabel(self.centralwidget)
        self.imageAudio1.setGeometry(QtCore.QRect(50, 70, 1031, 101))
        self.imageAudio1.setObjectName("imageAudio1")
        SynchWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SynchWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        SynchWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SynchWindow)
        self.statusbar.setObjectName("statusbar")
        SynchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SynchWindow)
        QtCore.QMetaObject.connectSlotsByName(SynchWindow)

    def retranslateUi(self, SynchWindow):
        _translate = QtCore.QCoreApplication.translate
        SynchWindow.setWindowTitle(_translate("SynchWindow", "MainWindow"))
        self.labelAudio1Value.setText(_translate("SynchWindow", "TextLabel"))
        self.imageAudio1.setText(_translate("SynchWindow", "imageaudio"))
